# Generated by Django 2.0.5 on 2018-05-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(blank=True, max_length=255, null=True)),
                ('mon', models.CharField(blank=True, max_length=255, null=True)),
                ('sun', models.CharField(blank=True, max_length=255, null=True)),
                ('others', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
