# Generated by Django 2.0.5 on 2018-05-29 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zones',
            old_name='mon',
            new_name='sat',
        ),
    ]
