# Generated by Django 2.0.5 on 2018-05-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180529_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(max_length=50, null=True, verbose_name='Track')),
                ('timezone', models.CharField(max_length=50, null=True, verbose_name='Timezone')),
                ('slotaday', models.CharField(max_length=50, null=True, verbose_name='SlotA day')),
                ('slota', models.TimeField(null=True, verbose_name='SlotA Time')),
                ('slotbday', models.CharField(max_length=50, null=True, verbose_name='SlotB day')),
                ('slotb', models.TimeField(null=True, verbose_name='SlotB Time')),
                ('stuname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Student Name')),
                ('pemail', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone Number')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
            ],
        ),
        migrations.AlterField(
            model_name='zones',
            name='sat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='zones',
            name='sun',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='zones',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
