# Generated by Django 2.0.5 on 2018-05-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180529_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='slota',
            field=models.CharField(max_length=50, null=True, verbose_name='SlotA Time'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slotb',
            field=models.CharField(max_length=50, null=True, verbose_name='SlotB Time'),
        ),
    ]
