# Generated by Django 2.0.5 on 2018-05-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180529_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='ist',
            field=models.CharField(max_length=50, null=True, verbose_name='Time in IST'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='pst',
            field=models.CharField(max_length=50, null=True, verbose_name='Time in PST'),
        ),
    ]
