# Generated by Django 2.0.5 on 2018-05-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180530_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zones',
            name='others',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zones',
            name='sat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zones',
            name='sun',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
