# Generated by Django 2.0.5 on 2018-06-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180530_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='contact',
            field=models.BooleanField(default=False, verbose_name='Contact'),
        ),
    ]
