# Generated by Django 2.0.5 on 2018-07-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_schedule_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='grade',
            field=models.CharField(max_length=20, null=True, verbose_name='Grade'),
        ),
    ]
